import { z } from 'zod'
import type { Hono } from 'hono'
import type { HonoEnv } from '../../types'
import { createAdminClient } from '../../services/supabase'
import { buildKey, KvCache } from '../../services/kv'
import { resolvePlan } from '../../services/plan'
import { generatePresignedPutUrl, randomId } from '../../services/r2'
import type { Broadcaster } from '../../services/realtime'

// ── Constants ──────────────────────────────────────────────────────────────────

const ALLOWED_TAGS = new Set([
  'vegan', 'vegetarian', 'spicy', 'gluten_free',
  'contains_nuts', 'halal', 'dairy_free', 'contains_alcohol',
])

const AVAILABILITY_STATES = ['available', 'unavailable', 'scheduled', 'out_of_stock'] as const

// ── Schemas ────────────────────────────────────────────────────────────────────

const tagsSchema = z
  .array(z.string())
  .optional()
  .superRefine((tags, ctx) => {
    if (!tags) return
    for (const tag of tags) {
      if (!ALLOWED_TAGS.has(tag)) {
        ctx.addIssue({ code: 'custom', message: `Unknown tag: ${tag}`, path: [] })
      }
    }
  })

const createItemSchema = z.object({
  name: z.string().min(1).max(150),
  description: z.string().optional(),
  price: z.number().gt(0),
  category_id: z.string().uuid(),
  availability_state: z.enum(AVAILABILITY_STATES).default('available'),
  tags: tagsSchema,
  // Null (or omitted) inherits the restaurant's special_requests_enabled default.
  special_requests_enabled: z.boolean().nullable().optional(),
})

const patchItemSchema = z.object({
  name: z.string().min(1).max(150).optional(),
  description: z.string().optional(),
  price: z.number().gt(0).optional(),
  category_id: z.string().uuid().optional(),
  availability_state: z.enum(AVAILABILITY_STATES).optional(),
  tags: tagsSchema,
  // Set after a successful PUT to the presigned URL from POST
  // /admin/menu/items/:id/image. Validated against the caller's own
  // restaurant_id + this item's id before persisting (see PATCH handler).
  image_r2_key: z.string().optional(),
  // Null inherits the restaurant's special_requests_enabled default.
  special_requests_enabled: z.boolean().nullable().optional(),
})

/** Matches the `<id>.<ext>` suffix generated by POST /admin/menu/items/:id/image. */
const ITEM_IMAGE_KEY_SUFFIX_RE = /^[a-z0-9]+\.[a-z]{3,4}$/

const availabilitySchema = z.object({
  state: z.enum(AVAILABILITY_STATES),
  restore_at: z.string().datetime().optional(),
})

const createVariantSchema = z.object({
  name: z.string().min(1).max(30),
  price: z.number().min(0),
  is_default: z.boolean().default(false),
  available: z.boolean().default(true),
})

const patchVariantSchema = z.object({
  name: z.string().min(1).max(30).optional(),
  price: z.number().min(0).optional(),
  is_default: z.boolean().optional(),
  available: z.boolean().optional(),
})

const variantReorderSchema = z
  .array(z.object({ id: z.string().uuid(), sort_order: z.number().int().min(0) }))
  .min(1)

const modifierAssignmentsSchema = z.object({
  group_ids: z.array(z.string().uuid()),
})

async function parseBody(req: Request): Promise<unknown> {
  try {
    return await req.json()
  } catch {
    return null
  }
}

// ── Deps ───────────────────────────────────────────────────────────────────────

export interface ItemRouteDeps {
  broadcaster?: Broadcaster
  generateUploadUrl?: (env: HonoEnv['Bindings'], key: string, expiresIn: number) => Promise<string>
}

// ── Route registration ─────────────────────────────────────────────────────────

export function registerItemRoutes(app: Hono<HonoEnv>, deps: ItemRouteDeps = {}): void {
  const getUploadUrl = deps.generateUploadUrl ?? generatePresignedPutUrl

  // ── GET /admin/menu/items ─────────────────────────────────────────────────

  app.get('/admin/menu/items', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const categoryId = c.req.query('category_id')

    const admin = createAdminClient(c.env)
    let q = admin
      .from('menu_items')
      .select('*, item_modifier_groups(modifier_group_id, modifier_groups(id, name))')
      .eq('restaurant_id', restaurantId)
      .eq('active', true)
      .order('sort_order', { ascending: true })

    if (categoryId) q = q.eq('category_id', categoryId)

    const { data, error } = await q
    if (error) return c.json({ error: 'fetch_failed' }, 500)

    const items = (data ?? []).map((item: Record<string, unknown>) => {
      const assignments = item['item_modifier_groups']
      const modifier_groups: Array<{ id: string; name: string }> = Array.isArray(assignments)
        ? assignments
            .map((a: Record<string, unknown>) => {
              const g = a['modifier_groups'] as { id: string; name: string } | null
              return g ? { id: g.id, name: g.name } : null
            })
            .filter((g): g is { id: string; name: string } => g !== null)
        : []
      const { item_modifier_groups: _, ...rest } = item
      return { ...rest, modifier_groups }
    })

    return c.json({ items })
  })

  // ── POST /admin/menu/items ────────────────────────────────────────────────

  app.post('/admin/menu/items', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!

    const parsed = createItemSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    const admin = createAdminClient(c.env)

    // item_cap check — resolve plan with DB fallback on KV miss
    const plan = await resolvePlan(c.env, restaurantId)
    const itemCap = typeof plan?.item_cap === 'number' ? plan.item_cap : null

    if (itemCap !== null) {
      const { count } = await admin
        .from('menu_items')
        .select('id', { count: 'exact', head: true })
        .eq('restaurant_id', restaurantId)
        .eq('active', true)
        .then((r) => ({ count: r.count ?? 0 }))

      if (count >= itemCap) {
        return c.json({ error: 'plan_limit_reached', limit: itemCap, current: count }, 402)
      }
    }

    const { data, error } = await admin
      .from('menu_items')
      .insert({ ...parsed.data, restaurant_id: restaurantId })
      .select()
      .single()

    if (error) {
      if (error.code === '23503') {
        const isCategoryFk = error.message?.includes('category_id')
        return isCategoryFk
          ? c.json({ error: 'category_not_found' }, 422)
          : c.json({ error: 'restaurant_not_found' }, 404)
      }
      return c.json({ error: 'create_failed' }, 500)
    }

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.json(data, 201)
  })

  // ── POST /admin/menu/items/reorder ───────────────────────────────────────
  // Must be registered before /:id routes so 'reorder' is not matched as an id.

  app.post('/admin/menu/items/reorder', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!

    const parsed = variantReorderSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    const admin = createAdminClient(c.env)
    const updates = await Promise.all(
      parsed.data.map(({ id, sort_order }) =>
        admin
          .from('menu_items')
          .update({ sort_order })
          .eq('id', id)
          .eq('restaurant_id', restaurantId),
      ),
    )

    if (updates.find((r) => r.error)) return c.json({ error: 'reorder_failed' }, 500)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.body(null, 204)
  })

  // ── PATCH /admin/menu/items/:id ───────────────────────────────────────────

  app.patch('/admin/menu/items/:id', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const id = c.req.param('id')

    const parsed = patchItemSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    // IDOR guard: image_r2_key must be this exact item's own generated key
    // (POST /admin/menu/items/:id/image always scopes it to
    // {restaurant_id}/{item_id}/…) — otherwise a caller could point an item's
    // image at another item's (or restaurant's) uploaded file.
    if (typeof parsed.data.image_r2_key === 'string') {
      const prefix = `${restaurantId}/${id}/`
      const suffix = parsed.data.image_r2_key.startsWith(prefix) ? parsed.data.image_r2_key.slice(prefix.length) : null
      if (!suffix || !ITEM_IMAGE_KEY_SUFFIX_RE.test(suffix)) {
        return c.json({ error: 'invalid_request', code: 'validation', issues: [{ path: ['image_r2_key'], message: 'must be a key generated by POST /admin/menu/items/:id/image for this item' }] }, 422)
      }
    }

    if (Object.keys(parsed.data).length === 0) {
      return c.json({ error: 'no_updatable_fields' }, 422)
    }

    const admin = createAdminClient(c.env)
    const { data, error } = await admin
      .from('menu_items')
      .update(parsed.data)
      .eq('id', id)
      .eq('restaurant_id', restaurantId)
      .select()
      .single()

    if (error || !data) return c.json({ error: 'not_found' }, 404)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.json(data)
  })

  // ── DELETE /admin/menu/items/:id ──────────────────────────────────────────

  app.delete('/admin/menu/items/:id', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const id = c.req.param('id')

    const admin = createAdminClient(c.env)
    const { data, error } = await admin
      .from('menu_items')
      .update({ active: false })
      .eq('id', id)
      .eq('restaurant_id', restaurantId)
      .select()
      .single()

    if (error || !data) return c.json({ error: 'not_found' }, 404)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.body(null, 204)
  })

  // ── POST /admin/menu/items/:id/image ─────────────────────────────────────

  app.post('/admin/menu/items/:id/image', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const itemId = c.req.param('id')

    // Check menu_photos feature flag — resolve plan with DB fallback on KV miss
    const plan = await resolvePlan(c.env, restaurantId)
    const flags = plan?.feature_flags as Record<string, unknown> | undefined
    const photosEnabled = flags?.menu_photos === true

    if (!photosEnabled) {
      return c.json(
        { error: 'feature_locked', feature: 'menu_photos', required_tier: 'growth' },
        402,
      )
    }

    const r2Key = `${restaurantId}/${itemId}/${randomId()}.webp`

    // Local dev: when R2 credentials aren't configured, return a Worker-handled
    // upload URL that stores directly to the MEDIA_BUCKET binding.
    const uploadUrl = c.env.R2_ACCOUNT_ID
      ? await getUploadUrl(c.env, r2Key, 15 * 60)
      : `${new URL(c.req.url).origin}/r2/${r2Key}`

    return c.json({ upload_url: uploadUrl, r2_key: r2Key }, 201)
  })

  // ── PATCH /admin/menu/items/:id/availability ──────────────────────────────

  app.patch('/admin/menu/items/:id/availability', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const id = c.req.param('id')

    const parsed = availabilitySchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    const admin = createAdminClient(c.env)
    const { data, error } = await admin
      .from('menu_items')
      .update({
        availability_state: parsed.data.state,
        restore_at: parsed.data.restore_at ?? null,
      })
      .eq('id', id)
      .eq('restaurant_id', restaurantId)
      .select()
      .single()

    if (error || !data) return c.json({ error: 'not_found' }, 404)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.json(data)
  })

  // ── GET /admin/menu/items/:item_id/modifier-assignments ──────────────────

  app.get('/admin/menu/items/:item_id/modifier-assignments', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const itemId = c.req.param('item_id')

    const admin = createAdminClient(c.env)

    const { data: item } = await admin
      .from('menu_items')
      .select('id')
      .eq('id', itemId)
      .eq('restaurant_id', restaurantId)
      .single()

    if (!item) return c.json({ error: 'not_found' }, 404)

    const { data, error } = await admin
      .from('item_modifier_groups')
      .select('modifier_group_id, sort_order')
      .eq('item_id', itemId)
      .order('sort_order', { ascending: true })

    if (error) return c.json({ error: 'fetch_failed' }, 500)

    return c.json({ group_ids: (data ?? []).map((r: { modifier_group_id: string }) => r.modifier_group_id) })
  })

  // ── PUT /admin/menu/items/:item_id/modifier-assignments ───────────────────

  app.put('/admin/menu/items/:item_id/modifier-assignments', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const itemId = c.req.param('item_id')

    const parsed = modifierAssignmentsSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    const admin = createAdminClient(c.env)

    const { data: item } = await admin
      .from('menu_items')
      .select('id')
      .eq('id', itemId)
      .eq('restaurant_id', restaurantId)
      .single()

    if (!item) return c.json({ error: 'not_found' }, 404)

    if (parsed.data.group_ids.length > 0) {
      const { data: groups } = await admin
        .from('modifier_groups')
        .select('id')
        .in('id', parsed.data.group_ids)
        .eq('restaurant_id', restaurantId)
        .is('item_id', null)

      if (!groups || groups.length !== parsed.data.group_ids.length) {
        return c.json({ error: 'invalid_group_ids' }, 422)
      }
    }

    const { error: delErr } = await admin
      .from('item_modifier_groups')
      .delete()
      .eq('item_id', itemId)

    if (delErr) return c.json({ error: 'update_failed' }, 500)

    if (parsed.data.group_ids.length > 0) {
      const rows = parsed.data.group_ids.map((gid, i) => ({
        item_id: itemId,
        modifier_group_id: gid,
        sort_order: i,
      }))

      const { error: insErr } = await admin
        .from('item_modifier_groups')
        .insert(rows)

      if (insErr) return c.json({ error: 'update_failed' }, 500)
    }

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.json({ group_ids: parsed.data.group_ids })
  })

  // ── GET /admin/menu/items/:item_id/variants ───────────────────────────────

  app.get('/admin/menu/items/:item_id/variants', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const itemId = c.req.param('item_id')

    const admin = createAdminClient(c.env)
    const { data, error } = await admin
      .from('item_variants')
      .select('*')
      .eq('item_id', itemId)
      .eq('restaurant_id', restaurantId)
      .order('sort_order', { ascending: true })

    if (error) return c.json({ error: 'fetch_failed' }, 500)

    return c.json({ variants: data ?? [] })
  })

  // ── POST /admin/menu/items/:item_id/variants ──────────────────────────────

  app.post('/admin/menu/items/:item_id/variants', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const itemId = c.req.param('item_id')

    const parsed = createVariantSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    const admin = createAdminClient(c.env)

    // Verify item belongs to this restaurant
    const { data: parentItem } = await admin
      .from('menu_items')
      .select('id')
      .eq('id', itemId)
      .eq('restaurant_id', restaurantId)
      .single()

    if (!parentItem) return c.json({ error: 'not_found' }, 404)

    // Count existing variants to determine sort_order + first-variant flag
    const { count: existingCount } = await admin
      .from('item_variants')
      .select('id', { count: 'exact', head: true })
      .eq('item_id', itemId)
      .eq('restaurant_id', restaurantId)
      .then((r) => ({ count: r.count ?? 0 }))

    const isFirst = existingCount === 0

    // If is_default: true, unset existing defaults first
    if (parsed.data.is_default) {
      await admin
        .from('item_variants')
        .update({ is_default: false })
        .eq('item_id', itemId)
        .eq('restaurant_id', restaurantId)
    }

    const { data, error } = await admin
      .from('item_variants')
      .insert({
        ...parsed.data,
        item_id: itemId,
        restaurant_id: restaurantId,
        sort_order: existingCount,
      })
      .select()
      .single()

    if (error || !data) return c.json({ error: 'create_failed' }, 500)

    // First variant: set has_variants = true on the parent item
    if (isFirst) {
      await admin
        .from('menu_items')
        .update({ has_variants: true })
        .eq('id', itemId)
        .eq('restaurant_id', restaurantId)
    }

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.json(data, 201)
  })

  // ── POST /admin/menu/items/:item_id/variants/reorder ─────────────────────

  app.post('/admin/menu/items/:item_id/variants/reorder', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!

    const parsed = variantReorderSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    const admin = createAdminClient(c.env)
    const updates = await Promise.all(
      parsed.data.map(({ id, sort_order }) =>
        admin
          .from('item_variants')
          .update({ sort_order })
          .eq('id', id)
          .eq('restaurant_id', restaurantId),
      ),
    )

    if (updates.find((r) => r.error)) return c.json({ error: 'reorder_failed' }, 500)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.body(null, 204)
  })

  // ── PATCH /admin/menu/variants/:id ────────────────────────────────────────

  app.patch('/admin/menu/variants/:id', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const id = c.req.param('id')

    const parsed = patchVariantSchema.safeParse(await parseBody(c.req.raw))
    if (!parsed.success) {
      return c.json({ error: 'invalid_request', code: 'validation', issues: parsed.error.issues }, 422)
    }

    if (Object.keys(parsed.data).length === 0) {
      return c.json({ error: 'no_updatable_fields' }, 422)
    }

    const admin = createAdminClient(c.env)

    // If setting is_default=true, unset siblings first
    if (parsed.data.is_default === true) {
      const { data: current } = await admin
        .from('item_variants')
        .select('item_id')
        .eq('id', id)
        .eq('restaurant_id', restaurantId)
        .single()

      if (current) {
        await admin
          .from('item_variants')
          .update({ is_default: false })
          .eq('item_id', (current as Record<string, unknown>).item_id as string)
          .eq('restaurant_id', restaurantId)
          .neq('id', id)
      }
    }

    const { data, error } = await admin
      .from('item_variants')
      .update(parsed.data)
      .eq('id', id)
      .eq('restaurant_id', restaurantId)
      .select()
      .single()

    if (error || !data) return c.json({ error: 'not_found' }, 404)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.json(data)
  })

  // ── DELETE /admin/menu/variants/:id ──────────────────────────────────────

  app.delete('/admin/menu/variants/:id', async (c) => {
    const jwt = c.get('jwt')
    const restaurantId = jwt.restaurant_id!
    const id = c.req.param('id')

    const admin = createAdminClient(c.env)

    // Fetch the variant to check is_default and item_id
    const { data: variant } = await admin
      .from('item_variants')
      .select('item_id, is_default, sort_order')
      .eq('id', id)
      .eq('restaurant_id', restaurantId)
      .single()

    if (!variant) return c.json({ error: 'not_found' }, 404)

    const v = variant as { item_id: string; is_default: boolean; sort_order: number }

    // Count siblings
    const { count: siblingCount } = await admin
      .from('item_variants')
      .select('id', { count: 'exact', head: true })
      .eq('item_id', v.item_id)
      .eq('restaurant_id', restaurantId)
      .neq('id', id)
      .then((r) => ({ count: r.count ?? 0 }))

    if (siblingCount === 0) {
      return c.json({ error: 'last_variant', message: 'Item must have at least one variant or a base price' }, 409)
    }

    // If deleting the default, promote next sibling by sort_order
    if (v.is_default) {
      const { data: nextVariant } = await admin
        .from('item_variants')
        .select('id')
        .eq('item_id', v.item_id)
        .eq('restaurant_id', restaurantId)
        .neq('id', id)
        .order('sort_order', { ascending: true })
        .limit(1)
        .single()

      if (nextVariant) {
        await admin
          .from('item_variants')
          .update({ is_default: true })
          .eq('id', (nextVariant as Record<string, unknown>).id as string)
          .eq('restaurant_id', restaurantId)
      }
    }

    const { error } = await admin
      .from('item_variants')
      .delete()
      .eq('id', id)
      .eq('restaurant_id', restaurantId)

    if (error) return c.json({ error: 'delete_failed' }, 500)

    await invalidateAndBroadcast(c.env, restaurantId, deps.broadcaster)

    return c.body(null, 204)
  })
}

// ── Helpers ────────────────────────────────────────────────────────────────────


async function invalidateAndBroadcast(
  env: HonoEnv['Bindings'],
  restaurantId: string,
  broadcaster?: Broadcaster,
): Promise<void> {
  // The public menu route (src/routes/public/menu.ts) reads/writes this cache
  // via MENU_CACHE, not SETTINGS_CACHE — deleting from the wrong binding is a
  // silent no-op, leaving the public menu stale for up to KV_TTLS.menu (300s)
  // after any edit.
  const cache = new KvCache(env.MENU_CACHE)
  await cache.delete(buildKey('menu', restaurantId))
  if (broadcaster) {
    broadcaster.broadcast(restaurantId, 'menu_availability_changed', {}, {} as ExecutionContext)
  }
}
