import { Hono } from 'hono'
import { getSwaggerUI } from 'chanfana'
import type { Env, HonoEnv } from './types'
import { corsMiddleware } from './middleware/cors'
import { buildOpenApiDocument } from './openapi/document'
import { registerHealthRoutes } from './routes/health'
import { registerAuthRoutes } from './routes/auth'
import { registerAdminRoutes } from './routes/admin'
import { registerSuperadminRoutes } from './routes/superadmin'
import { registerTabletRoutes } from './routes/tablet'
import { registerPublicRoutes } from './routes/public'
import { jwtMiddleware } from './middleware/jwt'
import { createSmartTransport } from './services/email-transport'
import { NotificationService } from './services/notifications'
import { runInventoryRestore, runAutoReject, runDeviceOfflineAlert } from './services/cron'

const app = new Hono<HonoEnv>()

// CORS first so cross-origin browser apps (and their preflights) are handled
// before any route logic.
app.use('*', corsMiddleware())

// Catch-all error handler — ensures unhandled exceptions return through Hono
// so the cors middleware's Access-Control-Allow-Origin header is always present.
app.onError((err, c) => {
  console.error('[unhandled]', err)
  return c.json({ error: 'internal_error' }, 500)
})

// ── R2 media serving / local-dev upload ────────────────────────────────────────
//
// GET  /r2/:key  — serve a media file from the MEDIA_BUCKET binding.
//                  In production this route should be behind a CDN (CF Pages /r2/*
//                  rewrite to the public R2 domain); it exists here so local dev
//                  and test environments can display uploaded images without a CDN.
//
// PUT  /r2/:key  — accept a raw file body and store it in MEDIA_BUCKET.
//                  Only available when R2_ACCOUNT_ID is unset (i.e. local dev).
//                  In production, clients upload directly to R2 via presigned URLs.

const ALLOWED_IMAGE_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'])

// UUID/UUID/... pattern — all keys generated by the Worker follow this shape.
const R2_KEY_RE = /^[0-9a-f-]{36}\/[0-9a-f-]{36}\/[a-z0-9]+\.[a-z]{3,4}$|^[0-9a-f-]{36}\/logo\/[a-z0-9]+\.[a-z]{3,4}$/

app.get('/r2/:key{.+}', async (c) => {
  const key = c.req.param('key')

  // Reject path traversal attempts and keys that don't match generated patterns.
  if (key.includes('..') || !R2_KEY_RE.test(key)) {
    return c.json({ error: 'not_found' }, 404)
  }

  const obj = await c.env.MEDIA_BUCKET.get(key)
  if (!obj) return c.json({ error: 'not_found' }, 404)

  // Never echo the stored content-type — a stored 'text/html' would be XSS.
  // Derive a safe type from the stored value; fall back to octet-stream.
  const stored = obj.httpMetadata?.contentType ?? ''
  const safeType = ALLOWED_IMAGE_TYPES.has(stored) ? stored : 'application/octet-stream'

  return new Response(obj.body, {
    headers: {
      'content-type': safeType,
      'content-disposition': 'inline',
      'cache-control': 'public, max-age=31536000, immutable',
      'x-content-type-options': 'nosniff',
      'content-security-policy': "default-src 'none'; sandbox",
    },
  })
})

app.put('/r2/:key{.+}', jwtMiddleware, async (c) => {
  // Local-dev upload path — blocked in production where R2_ACCOUNT_ID is set.
  if (c.env.R2_ACCOUNT_ID) {
    return c.json({ error: 'direct_upload_not_available' }, 403)
  }

  // IDOR guard: the key must be scoped to the caller's restaurant.
  const jwt = c.get('jwt')
  const key = c.req.param('key')
  if (!key.startsWith(`${jwt.restaurant_id}/`)) {
    return c.json({ error: 'forbidden' }, 403)
  }

  // Only accept safe image content-types.
  const contentType = c.req.header('content-type') ?? ''
  if (!ALLOWED_IMAGE_TYPES.has(contentType)) {
    return c.json({ error: 'invalid_content_type' }, 415)
  }

  const body = await c.req.arrayBuffer()
  await c.env.MEDIA_BUCKET.put(key, body, { httpMetadata: { contentType } })
  return c.body(null, 204)
})

// API documentation. Routes are plain Hono handlers (not Chanfana route
// classes), so we serve a hand-authored OpenAPI 3.1 document and render it with
// Chanfana's Swagger UI helper. Full decorator-based generation lands in the
// complete STORY-044.
const openApiDocument = buildOpenApiDocument()
app.get('/openapi.json', () => Response.json(openApiDocument))
app.get('/docs', (c) => c.html(getSwaggerUI('/openapi.json')))

const emailDeps = { transport: () => createSmartTransport() }
const notifier = (env: Env) => new NotificationService(env, createSmartTransport())

registerHealthRoutes(app)
registerAuthRoutes(app)
registerPublicRoutes(app, { notifier })
registerAdminRoutes(app, { ...emailDeps, notifier })
registerSuperadminRoutes(app, emailDeps)
registerTabletRoutes(app, { notifier })

// Attach the scheduled handler directly to the Hono app instance so tests
// can still call app.request() while the CF Workers runtime gets the
// scheduled() method it needs for cron triggers.
const appWithCron = Object.assign(app, {
  async scheduled(_event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(
      Promise.all([
        runInventoryRestore(env, ctx),
        runAutoReject(env, ctx),
        runDeviceOfflineAlert(env, notifier),
      ]),
    )
  },
})

export { app }
export { TenantCounterDO } from './durable/TenantCounterDO'
export default appWithCron
