import { Hono } from 'hono'
import { getSwaggerUI } from 'chanfana'
import type { HonoEnv } from './types'
import { corsMiddleware } from './middleware/cors'
import { buildOpenApiDocument } from './openapi/document'
import { registerHealthRoutes } from './routes/health'
import { registerAuthRoutes } from './routes/auth'
import { registerAdminRoutes } from './routes/admin'
import { registerSuperadminRoutes } from './routes/superadmin'
import { registerTabletRoutes } from './routes/tablet'
import { jwtMiddleware } from './middleware/jwt'

const app = new Hono<HonoEnv>()

// CORS first so cross-origin browser apps (and their preflights) are handled
// before any route logic.
app.use('*', corsMiddleware())

// ── R2 media serving / local-dev upload ────────────────────────────────────────
//
// GET  /r2/:key  — serve a media file from the MEDIA_BUCKET binding.
//                  In production this route should be behind a CDN (CF Pages /r2/*
//                  rewrite to the public R2 domain); it exists here so local dev
//                  and test environments can display uploaded images without a CDN.
//
// PUT  /r2/:key  — accept a raw file body and store it in MEDIA_BUCKET.
//                  Only available when R2_ACCOUNT_ID is unset (i.e. local dev).
//                  In production, clients upload directly to R2 via presigned URLs.

const ALLOWED_IMAGE_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'])

// UUID/UUID/... pattern — all keys generated by the Worker follow this shape.
const R2_KEY_RE = /^[0-9a-f-]{36}\/[0-9a-f-]{36}\/[a-z0-9]+\.[a-z]{3,4}$|^[0-9a-f-]{36}\/logo\/[a-z0-9]+\.[a-z]{3,4}$/

app.get('/r2/:key{.+}', async (c) => {
  const key = c.req.param('key')

  // Reject path traversal attempts and keys that don't match generated patterns.
  if (key.includes('..') || !R2_KEY_RE.test(key)) {
    return c.json({ error: 'not_found' }, 404)
  }

  const obj = await c.env.MEDIA_BUCKET.get(key)
  if (!obj) return c.json({ error: 'not_found' }, 404)

  // Never echo the stored content-type — a stored 'text/html' would be XSS.
  // Derive a safe type from the stored value; fall back to octet-stream.
  const stored = obj.httpMetadata?.contentType ?? ''
  const safeType = ALLOWED_IMAGE_TYPES.has(stored) ? stored : 'application/octet-stream'

  return new Response(obj.body, {
    headers: {
      'content-type': safeType,
      'content-disposition': 'inline',
      'cache-control': 'public, max-age=31536000, immutable',
      'x-content-type-options': 'nosniff',
      'content-security-policy': "default-src 'none'; sandbox",
    },
  })
})

app.put('/r2/:key{.+}', jwtMiddleware, async (c) => {
  // Local-dev upload path — blocked in production where R2_ACCOUNT_ID is set.
  if (c.env.R2_ACCOUNT_ID) {
    return c.json({ error: 'direct_upload_not_available' }, 403)
  }

  // IDOR guard: the key must be scoped to the caller's restaurant.
  const jwt = c.get('jwt')
  const key = c.req.param('key')
  if (!key.startsWith(`${jwt.restaurant_id}/`)) {
    return c.json({ error: 'forbidden' }, 403)
  }

  // Only accept safe image content-types.
  const contentType = c.req.header('content-type') ?? ''
  if (!ALLOWED_IMAGE_TYPES.has(contentType)) {
    return c.json({ error: 'invalid_content_type' }, 415)
  }

  const body = await c.req.arrayBuffer()
  await c.env.MEDIA_BUCKET.put(key, body, { httpMetadata: { contentType } })
  return c.body(null, 204)
})

// API documentation. Routes are plain Hono handlers (not Chanfana route
// classes), so we serve a hand-authored OpenAPI 3.1 document and render it with
// Chanfana's Swagger UI helper. Full decorator-based generation lands in the
// complete STORY-044.
const openApiDocument = buildOpenApiDocument()
app.get('/openapi.json', () => Response.json(openApiDocument))
app.get('/docs', (c) => c.html(getSwaggerUI('/openapi.json')))

registerHealthRoutes(app)
registerAuthRoutes(app)
registerAdminRoutes(app)
registerSuperadminRoutes(app)
registerTabletRoutes(app)

export default app
export { app }
